version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch01
    restart: always
    environment:
      - node.name=elasticsearch01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  data01:
    driver: local
